config/routes.rb
Rails.application.routes.draw do
  # ==== HELP CENTER ROUTES === #
  get 'help', to: 'help#index'

  get 'help/about', to: 'help#about'
  get 'help/about/whats-this', to: 'help_about#whats_this'
  get 'help/about/contact', to: 'help_about#contact'

  get 'help/contacts', to: 'help#contacts'
  get 'help/contacts/details', to: 'help_contacts#details'
  get 'help/contacts/creating', to: 'help_contacts#creating'
  get 'help/contacts/managing', to: 'help_contacts#managing'

  get 'help/security', to: 'help#security'
  get 'help/security/tech', to: 'help_security#tech'
  get 'help/security/bugs', to: 'help_security#bugs'

  # === ADMIN ROUTES === #
  get 'admin', to: 'admin#index'
  get 'admin/users', to: 'users#index'
  get 'admin/contacts', to: 'contacts#show_all'

  get 'admin/notices', to: 'site_notices#index'
  get 'admin/notices/new', to: 'site_notices#new'
  post 'admin/notices/new', to: 'site_notices#create'
  get 'admin/notices/:id/edit', to: 'site_notices#edit'
  put 'admin/notices/:id/edit', to: 'site_notices#update'
  patch 'admin/notices/:id/edit', to: 'site_notices#update'
  delete 'admin/notices/:id', to: 'site_notices#destroy'

  get 'admin/users/:id', to: 'users#admin_options'
  post 'admin/users/:id/edit', to: 'users#admin_edit'
  patch 'admin/users/:id/edit', to: 'users#admin_edit'
  delete 'admin/users/:id', to: 'users#admin_delete'

  # === EXPORTS ROUTES === #
  get 'exports/json', to: 'exports#json'
  get 'exports/xml', to: 'exports#xml'
  get 'exports/vcf/:id', to: 'exports#vcard'

  # === SESSION MANAGEMENT ROUTES === #
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#login_attempt'
  get 'logout', to: 'sessions#logout'

  get 'sign-up', to: 'users#new'
  post 'sign-up', to: 'users#create'

  # === ACCOUNT MANAGEMENT ROUTES === #
  get 'dashboard', to: 'sessions#home'
  get 'profile', to: 'sessions#profile'
  get 'settings', to: 'sessions#settings'
  get 'users/confirm', to: 'users#confirm'

  # === CONTACTS ROUTES === #
  get 'contacts/encrypt', to: 'contacts#encrypt'
  post 'contacts/encrypt', to: 'contacts#do_encrypt'
  resources :contacts

  # === SPECIAL ROUTES === #
  root to: 'dynamic_routes#root'
end

app/models/contact.rb
class Contact < ActiveRecord::Base 
  def self.encrypted_fields
    return ['first', 'last', 'title', 'city', 'phone', 'email']
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :check_ownership, except: [:index, :new, :create, :show_all, :encrypt, :do_encrypt]
  before_action :decrypt_set_contact, only: [:show, :edit]
  before_action :verify_admin, only: [:show_all]

  rescue_from ActiveRecord::RecordNotFound, :with => :render_403

  # GET /contacts/all
  def show_all
    @contacts = Contact.joins("inner join users on contacts.created_by = users.id")
      .select("contacts.created_by, contacts.id, contacts.title, contacts.first, contacts.last, contacts.city, contacts.phone, contacts.email, users.username")
    # Don't bother decrypting these contacts; administrators won't be able to decrypt everything because DEKs are based
    # on passwords. Only some contacts (their own) would show in plain text.
  end

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.select("id, title, first, last, city, phone, email").where("created_by" => @current_user.id)
    @contacts = decrypt_contacts(@contacts)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.created_by = @current_user.id

    @contact = encrypt_contacts(@contact)

    respond_to do |format|
      if @contact.save
        format.html {
          flash[:notice] = "Contact was successfully created."
          flash[:color] = "valid"
          redirect_to action: "index"
        }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    # Because we're encrypting, just updating the old contact leaves a point of vulnerability at which the plaintext
    # details are in the database. To avoid that, destroy the old record and replace it with a new one, which is
    # encrypted before it ever hits the database.
    old_contact = Contact.find(params[:id])
    old_contact.destroy

    @contact = Contact.new(contact_params)
    @contact.id = params[:id]
    @contact.created_by = @current_user.id

    @contact = encrypt_contacts(@contact)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def encrypt
  end

  def do_encrypt
    @contacts = Contact.where(:created_by => @current_user.id, :is_encrypted => false)
    puts "Found #{@contacts.count} contacts by user #{@current_user.id} with :is_encrypted => false"
    @contacts.each do |contact|
      contact = encrypt_contacts(contact)
      contact.is_encrypted = true
      contact.save
    end
    flash[:notice] = "Your contacts were successfully encrypted."
    flash[:color] = "valid"
    render :encrypt
  end


  # Methods that are specific to contacts operations.
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def decrypt_set_contact
      @contact = decrypt_contacts(@contact)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first, :last, :title, :city, :phone, :email)
    end

    def check_ownership
      if @contact.created_by != @current_user.id
        render_403
      end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/encrypt.html.erb
<h1>Encrypt Contacts</h1>
<p>Encryption of new contacts was added on March 27, 2016. This means that any contacts you create will now be encrypted
  before they are saved - meaning no plain text contact details ever get stored in the database for new contacts.</p>
<p>Now I'm widening the scope of this feature to existing contacts too. However, I don't have access to your decryption
  key, so this needs action from you to complete. There are a few simple steps you need to follow to add encryption to
  all your existing contacts.</p>
<ul>
  <li>Log out, then log back in again. This is to refresh your session - by doing this, the site can create your
    decryption key, which it will use to encrypt all your contacts.</li>
  <li>Click the "Encrypt Contacts Now" button below. This performs the encryption. Depending on how many contacts you
    have created, this may take up to a minute - please be patient.</li>
</ul><br/>
<%= link_to "Encrypt Contacts Now", { :action => :do_encrypt },
    :method => :post, data: { :confirm => "Start encrypting contacts?" }, :class => "button" %>
<br/>

app/views/contacts/index.html.erb
<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th class="expanded-view">Title</th>
      <th class="expanded-view">City</th>
      <th class="expanded-view">Phone</th>
      <th class="expanded-view">Email</th>
      <th></th>
      <th class="expanded-view"></th>
      <th class="expanded-view"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first.truncate(15) %></td>
        <td><%= contact.last.truncate(15) %></td>
        <td class="expanded-view"><%= contact.title.truncate(15) %></td>
        <td class="expanded-view"><%= contact.city.truncate(15) %></td>
        <td class="expanded-view"><%= contact.phone.truncate(15) %></td>
        <td class="expanded-view"><%= contact.email.truncate(15) %></td>
        <td><%= link_to 'Show', contact %></td>
        <td class="expanded-view"><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td class="expanded-view"><%= link_to 'Delete', contact, :method => :delete, data: { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %> |
<a href="/exports/json">Export all as JSON</a> |
<a href="/exports/xml">Export all as XML</a>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>First:</strong>
  <%= @contact.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @contact.last %>
</p>

<p>
  <strong>Title:</strong>
  <%= @contact.title %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Delete', @contact, :method => :delete, data: { :confirm => 'Are you sure?' } %> |
<%= link_to 'Back', contacts_path %> |
<a href="/exports/vcf/<%= @contact.id %>">Export as vCard</a>

app/views/contacts/show_all.html.erb
<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Owner</th>
      <th class="expanded-view">First</th>
      <th class="expanded-view">Last</th>
      <th class="expanded-view">Title</th>
      <th class="expanded-view">City</th>
      <th class="expanded-view">Phone</th>
      <th class="expanded-view">Email</th>
      <th class="expanded-view"></th>
      <th class="expanded-view"></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.id %></td>
        <td><%= contact.username %></td>
        <td class="expanded-view"><%= contact.first.truncate(15) %></td>
        <td class="expanded-view"><%= contact.last.truncate(15) %></td>
        <td class="expanded-view"><%= contact.title.truncate(15) %></td>
        <td class="expanded-view"><%= contact.city.truncate(15) %></td>
        <td class="expanded-view"><%= contact.phone.truncate(15) %></td>
        <td class="expanded-view"><%= contact.email.truncate(15) %></td>
        <td class="expanded-view"><% if contact.created_by == @current_user.id %>
              <%= link_to 'Show', contact %>
            <% end %></td>
        <td class="expanded-view"><% if contact.created_by == @current_user.id %>
              <%= link_to 'Edit', edit_contact_path(contact) %>
            <% end %></td>
        <td><%= link_to 'Delete', contact, :method => :delete, data: { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>